env: "dev" # "dev", "prod"

server:
  address: ":8080"
  readTimeout: "5s"
  writeTimeout: "5s"
  idleTimeout: "60s"

database:
  host: "db"
  port: 5432
  user: "prw"
  password: "prw"
  name: "prw"
  sslmode: "disable"
  pool:
    maxOpenConns: 15
    maxIdleConns: 15
    connMaxLifetime: "30m"
